name: tamir_kolay
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  equatable: ^2.0.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: 6.1.0
  image_picker: ^1.1.1
  intl: ^0.18.1
  json_annotation: ^4.9.0
  kartal: ^3.5.0
  liquid_pull_to_refresh: ^3.0.1
  mockito: ^5.4.4
  responsive_sizer: ^3.3.0+1
  riverpod: ^2.5.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  test: ^1.24.9
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  wolt_modal_sheet: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
