// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGp5hS9TAxmhsH196b-ceRm70pC346L3M',
    appId: '1:1017673690753:web:067617ee0588cc54766780',
    messagingSenderId: '1017673690753',
    projectId: 'tamir-kolay-3c428',
    authDomain: 'tamir-kolay-3c428.firebaseapp.com',
    databaseURL: 'https://tamir-kolay-3c428-default-rtdb.firebaseio.com',
    storageBucket: 'tamir-kolay-3c428.appspot.com',
    measurementId: 'G-1G2WYZNS67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg8MAIvtEah9NWP_lVo44xii6Q7Ndi890',
    appId: '1:1017673690753:android:4f5549c0a0ddc3ed766780',
    messagingSenderId: '1017673690753',
    projectId: 'tamir-kolay-3c428',
    databaseURL: 'https://tamir-kolay-3c428-default-rtdb.firebaseio.com',
    storageBucket: 'tamir-kolay-3c428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtsnfB8rQnJxVGH61fsP7kOpNOz3cMN4w',
    appId: '1:1017673690753:ios:abcb54c1e7e2c877766780',
    messagingSenderId: '1017673690753',
    projectId: 'tamir-kolay-3c428',
    databaseURL: 'https://tamir-kolay-3c428-default-rtdb.firebaseio.com',
    storageBucket: 'tamir-kolay-3c428.appspot.com',
    iosBundleId: 'com.example.tamirKolay',
  );
}
